### ISSUE TITLE
Illegal Color Name

### ISSUE THREAD

**Issue by philcockfield** [brijeshb42/monaco-themes#1]
Hey thanks @brijeshb42 for making these themes.  This is so jolly helpful!

----

I'm trying to get this working using the "[Directly with Webpack](https://github.com/brijeshb42/monaco-themes#with-webpack)" approach:

```js
   const monokai = require('monaco-themes/themes/Monokai.json');

    monaco.editor.defineTheme('monokai', monokai);
    monaco.editor.setTheme('monokai');

```
and I'm getting an error.

![image](https://user-images.githubusercontent.com/185555/44113825-79a1339c-a05d-11e8-90c8-9e66d94f59b3.png)

Looks like it's bawking at the hex color values.  Any ideas on what I might be doing wrong here?  Thanks!

**Comment by brijeshb42** [comment]
Seems to be working fine for me


<img width="1262" alt="screen shot 2018-08-15 at 9 24 49 am" src="https://user-images.githubusercontent.com/717550/44130859-29d8b776-a06d-11e8-96ef-627b6d221b6c.png">

What version of `monaco` are you using?

**Comment by philcockfield** [comment]
Ah, I'll check out the version - could well be that!  Thanks for confirming what I'm doing should work @brijeshb42.

And thanks again for these themes.  Not having `monokai` makes me 😞 .... 😃

**Comment by gunn** [comment]
Fails for me as well with monaco 0.13.1 and 0.14.2.

I can fix this by:
Removing all the `#`s from the colors except the ones in the `colors` object.
And making sure colors are 6 characters, not 8. I.e. `ff6600ff` -> `ff6600`

This also matches what we see in monaco's doumentation - https://github.com/Microsoft/monaco-editor/blob/088301bfb99/website/playground/new-samples/customizing-the-appearence/tokens-and-colors/sample.js#L17

**Comment by brijeshb42** [comment]
I don't think `#` and 8 digit hex codes are the issue. I can see that in [`vs/editor/common/modes/supports/tokenization.ts`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/supports/tokenization.ts#L150) the regex that is being used to parse hex colors gives the base 6 digit hex code and alpha code which is then used in the editor. I have setup another project @ https://editor-a5ea1.firebaseapp.com/ using webpack with themes as a dependency. But that is also working without any errors.

Can you guys tell me which language are you using in the editor when this error comes up? Maybe that can help me in identifying the bug.

Meanwhile, I have published a beta version which has only 6 char hex code and no `#`. Can you try to install that using `npm install monaco-themes@beta` and see if the error comes or not?

**Comment by philcockfield** [comment]
I'm on version `0.14.1` of monaco-editor via [react-monaco-editor](https://github.com/superRaytin/react-monaco-editor)

I'm setting the custom theme in the `didMount` callback handler

```ts
        <MonacoEditor
         ...
          editorDidMount={this.handleAfterMount}
        />

=``

which is where other config manipulation at setup is going:

```ts
    private handleAfterMounted = (
      editor: ICodeEditor,
    ) => {

      // Configure Monki theme.
      // https://github.com/brijeshb42/monaco-themes
      monaco.editor.defineTheme(
        'monokai',
        monokai as monaco.editor.IStandaloneThemeData,
      );
      monaco.editor.setTheme('monokai');
    };

```

Thanks @brijeshb42

**Comment by philcockfield** [comment]
Just checked - your definition for `monokai` in `monaco-themes@beta` is working for me @brijeshb42 

Thanks.

**Comment by brijeshb42** [comment]
Published the `beta` to `stable`
