### ISSUE TITLE
trying to convert .tmTheme to monaco theme online

### ISSUE THREAD

**Issue by jkuri** [brijeshb42/monaco-themes#13]
Hi, 

I am trying to convert [.tmTheme](https://raw.githubusercontent.com/akamud/vscode-theme-onelight/master/themes/OneLight.old.tmTheme) to monaco theme using your online demo at https://bitwiser.in/monaco-themes/. I tried to upload this theme so it can convert it automatically but file does not seem to get uploaded, can you please check on that?

Thanks, Jan

**Comment by brijeshb42** [comment]
Is this in Firefox?

**Comment by jkuri** [comment]
no, I am using latest Chrome 83.0.4103.116.

**Comment by jkuri** [comment]
nevermind, I got it converted with cloning the repo. thanks.
