### ISSUE TITLE
Feature Request: Type Definitions / TypeScript

### ISSUE THREAD

**Issue by LeoDog896** [brijeshb42/monaco-themes#31]
Type definitions for this project would be great!

**Comment by brijeshb42** [comment]
How are you using this? Could you share a code snippet?

**Comment by LeoDog896** [comment]
Hi! I forgot about this issue 😅 - I used to use `parseTmThemes`, but the function itself didn't have `.d.ts` types, so I typed it locally - however, I now directly use the theme itself - typings _may_ be useful but it may be better to encourage users to use the json themes directly.
