### ISSUE TITLE
Feature Request: Semantic Highlighting support

### ISSUE THREAD

**Issue by EvanWiederspan** [brijeshb42/monaco-themes#32]
It'd be nice if these themes supported extra styling for when semantic highlighting is enabled, https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide

**Comment by brijeshb42** [comment]
> Semantic tokenization allows language servers to provide additional token information based on the language server's knowledge on how to resolve symbols in the context of a project. 

This particular feature depends on the language server as well and cannot achieved in a standalone way. So closing this.
