### ISSUE TITLE
[Question] Is the VSCode Dark+ theme compatible with the Monaco Themes?

### ISSUE THREAD

**Issue by dnmd** [brijeshb42/monaco-themes#4]
First of, thanks for providing these themes! Great job! I've got a question though, whether or not;

a) it is possible to "port" VSCode its Dark+ theme?
b) if so, do you have any recommendations / pointers in doing so?

Thanks in advance, and again, thanks!

**Comment by brijeshb42** [comment]
It won't be directly compatible. You'll have to create a function to transform one theme to the other. 
vscode theme json has 2 main attributes - `tokenColors` and `colors`. monaco's theme has `rules` and `colors`. So the function will have to convert data in `tokenColors` to `rules`.

**Comment by schickling** [comment]
> You'll have to create a function to transform one theme to the other.

@brijeshb42 are you aware of someone already having written this function? (Also see [my question on SO](https://stackoverflow.com/questions/65959169/how-to-use-a-vsc-theme-in-monaco-editor).)
